name: build
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Package
        uses: DuckSoft/build-aur-action@master
        with:
          repo-name: git-delta-bin
